name: Releases
on:
  push:
    tags:
      - '*'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: git checkout
      uses: actions/checkout@v1

    - name: Run tests
      run: go test ./...

    - name: Build
      run: ./build.sh

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "hash-cracker_*"
        token: ${{ secrets.GITHUB_TOKEN }}

